# Generated by Django 3.1 on 2023-03-12 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255, verbose_name='Genre name')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='News content')),
                ('newsDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('newsImage', models.CharField(default='', max_length=255, verbose_name="Book's image")),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reviewContent', models.TextField(verbose_name='Review content')),
                ('reviewDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('reviewImage', models.CharField(default='', max_length=255, verbose_name="Book's image")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=255, verbose_name='Book name')),
                ('bookAuthor', models.CharField(max_length=255, verbose_name="Book's author")),
                ('pages', models.IntegerField(verbose_name="Book's pages")),
                ('description', models.TextField(verbose_name="Book's description")),
                ('price', models.FloatField(verbose_name='Price')),
                ('bookImage', models.CharField(default='', max_length=255, verbose_name="Book's image")),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShop.genre')),
            ],
        ),
    ]
